spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mydatabase
    username: myuser
    password: secret

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

#  sql:
#    init:
#      mode: always

  jpa:
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        default-schema: my_schema